### PR TITLE
Add slicing to ContResult

### PR DESCRIPTION
**Pull request by twildi**
As one can index into ContResult, it would probably make some sense to be able to slice into it as well.

### CODE REVIEW

**Comment by rveltz** [comment]
Hi,

Thank you for the PR!
How did you come to this, do you find it useful?

Can you add some test to ensure the coverage please?

**Comment by twildi** [comment]
I wanted to plot only a subset of the continuation results while still benefiting from the syntactic sugar of the built-in plot methods. Something like  
```
plot(br1[40:60], br2[5:end], vars=(:x, :y))
```
instead of 
```
plot(br1.x[40:60], br1.y[40:60])
plot!(br2.x[5:end], br2.y[5:end])
scatter!([br1[sp.idx].x for sp in br1.specialpoint if sp.step in 40:60], 
    [br1[sp.idx].y for sp in br1.specialpoint if sp.step in 40:60])
...
```
If this is of interest, I'll play around with it some more and add some tests.

**Comment by rveltz** [comment]
Yes, it is a cool idea! If you add a test, Ill merge your PR.

**Comment by twildi** [comment]
Okay, I think it's ready to merge.

I also fixed a bug in `Base.getindex(br::ContResult, k::Int)` where in the case of `save_eig_every_step >= 2` and/or `save_sol_every_step >= 2` indexing into the `ContResult` would return the eigenvalues/eigenvectors/solution for the wrong step.

**Comment by rveltz** [comment]
Great for solving the bug I did not see. Thank you for all this !!!

**Pull request merged**
