### PR TITLE
chore: bump RecursiveArrayTools compat

### PR DESCRIPTION
**Pull request by AayushSabharwal**
This is for the upcoming RecursiveArrayTools.jl v3 release, in https://github.com/SciML/RecursiveArrayTools.jl/pull/290

Tests won't pass for a while, since there's an entire dependency tree that needs to be merged first

### CODE REVIEW

**Comment by rveltz** [comment]
I guess I need to wait until the release. Thank you for pointing this out

**Comment by ChrisRackauckas** [comment]
It's released.

**Comment by ven-k** [comment]
Bump

**Comment by AayushSabharwal** [comment]
I ran tests locally and they pass
```
Test Summary:  |  Pass  Total       Time
BifurcationKit | 12867  12867  112m59.6s
     Testing BifurcationKit tests passed
```

**Comment by chriselrod** [comment]
Bump

**Comment by rveltz** [comment]
Arrrggg

I merged this PR because the tests look fine but it leads to a lot of errors. For example the test https://buildkite.com/julialang/bifurcationkit-dot-jl/builds/80#018c8b0e-5ec9-4807-a216-f07ec000586b
shows a lot of them. One is in `Preconditioner.jl` which is kinda OK but a lot pop up from `flowDE.jl`

**Pull request merged**
